# Generated by Django 2.2.6 on 2019-10-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
