# Generated by Django 2.2.6 on 2019-10-14 23:05

import custom_fields.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0003_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='full_name',
            field=custom_fields.models.NameField(max_length=20),
        ),
    ]
