# Generated by Django 2.2.6 on 2019-10-15 00:34

import custom_fields.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0004_auto_20191014_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=custom_fields.models.RoleField(max_length=20),
        ),
    ]
