# Generated by Django 2.2.6 on 2019-10-15 01:08

import custom_fields.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0005_auto_20191015_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='gender',
            field=custom_fields.models.GenderField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6),
        ),
    ]
