# Generated by Django 2.2.6 on 2019-10-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0006_auto_20191015_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
