# Generated by Django 2.2.6 on 2019-10-15 18:21

import custom_fields.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0007_developer_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='company',
            field=custom_fields.models.CompanyField(max_length=51),
        ),
        migrations.AlterField(
            model_name='developer',
            name='full_name',
            field=custom_fields.models.NameField(max_length=21),
        ),
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=custom_fields.models.RoleField(choices=[('BACK-END DEVELOPER', 'Back-end Developer'), ('FRONT-END DEVELOPER', 'Front-end Developer'), ('FULL STACK DFEVELOPER', 'Full Stack Developer'), ('ANDROID DEVELOPER', 'Android Developer'), ('IOS DEVELOPER', 'iOS Developer'), ('DESIGNER', 'Designer')], max_length=50),
        ),
    ]
