# Generated by Django 2.2.6 on 2019-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields_app', '0008_auto_20191015_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
